require "cucumber/rake/task"

Cucumber::Rake::Task.new(:run) do |task|

    #task.cucumber_opts = ["features"]
    task.cucumber_opts = ["-t","@#{ENV["TAG"] || "all" }","features"]
end

Cucumber::Rake::Task.new(:compile) do |task|

    task.cucumber_opts = ["-t","@compile","features"]
end

Cucumber::Rake::Task.new(:list) do |task|

    task.cucumber_opts = ["-d", "-f", "PrintSteps", "-t","@#{ENV["TAG"] || "all" }","features"]
end